"""Generate stable identifiers for AIS assignment acknowledgements."""

from alembic import op

revision = "0004_ais_assignment_identity"
down_revision = "0003_ais_order_weight"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE ais.ais_assignments "
        "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE ais.ais_assignments ALTER COLUMN id DROP IDENTITY IF EXISTS")
