export const operatorSets: Record<string, string[]> = {
  string: [
    "=",
    "!=",
    "starts_with",
    "ends_with",
    "contains_substr",
    "regex",
    "is_null",
    "not_null",
  ],
  number: [
    "=",
    "!=",
    ">",
    ">=",
    "<",
    "<=",
    "between",
    "in",
    "not_in",
    "is_null",
    "not_null",
  ],
  boolean: ["=", "!=", "implies", "is_null", "not_null"],
  date: ["=", "!=", ">", ">=", "<", "<=", "within_last", "is_null", "not_null"],
  enum: [
    "=",
    "!=",
    "in",
    "not_in",
    "contains",
    "contains_any",
    "contains_all",
    "intersects",
    "is_empty",
    "is_null",
    "not_null",
  ],
  string_array: [
    "contains",
    "contains_any",
    "contains_all",
    "intersects",
    "is_empty",
    "is_null",
    "not_null",
  ],
};

export const operatorLabels: Record<string, string> = {
  "=": "равно",
  "!=": "не равно",
  ">": "больше",
  ">=": "не меньше",
  "<": "меньше",
  "<=": "не больше",
  starts_with: "начинается с",
  ends_with: "заканчивается на",
  contains_substr: "содержит текст",
  regex: "регулярное выражение",
  between: "между",
  in: "в списке",
  not_in: "не в списке",
  implies: "влечёт",
  within_last: "за последнее время",
  contains: "содержит элемент",
  contains_any: "содержит любой",
  contains_all: "содержит все",
  intersects: "пересекается",
  is_empty: "пусто",
  is_null: "не задано",
  not_null: "задано",
};
